from typing import List, Dict
from app.models.factor import FactorDefinition, FactorCategory, MissingValuePolicy, ParameterSchema


def _make_def(factor_id: str, name: str, category: FactorCategory, desc: str, params: List[dict] = None) -> FactorDefinition:
    param_models = [ParameterSchema(**p) for p in (params or [])]
    return FactorDefinition(
        factor_id=factor_id,
        name=name,
        category=category,
        description=desc,
        parameters=param_models
    )


# Exact 171-factor catalog
FACTOR_CATALOG: List[FactorDefinition] = [
    # 1. Price / Return (18)
    _make_def("ret_1d", "1日收益率", FactorCategory.PRICE, "过去1个交易日对数或百分比收益率"),
    _make_def("ret_5d", "5日收益率", FactorCategory.PRICE, "过去5个交易日累计收益率"),
    _make_def("ret_10d", "10日收益率", FactorCategory.PRICE, "过去10个交易日累计收益率"),
    _make_def("ret_20d", "20日收益率", FactorCategory.PRICE, "过去20个交易日累计收益率"),
    _make_def("ret_60d", "60日收益率", FactorCategory.PRICE, "过去60个交易日累计收益率"),
    _make_def("ret_120d", "120日收益率", FactorCategory.PRICE, "过去120个交易日累计收益率"),
    _make_def("ret_240d", "240日收益率", FactorCategory.PRICE, "过去240个交易日累计收益率"),
    _make_def("log_ret_1d", "1日对数收益率", FactorCategory.PRICE, "1日对数收益率"),
    _make_def("log_ret_5d", "5日对数收益率", FactorCategory.PRICE, "5日对数收益率"),
    _make_def("log_ret_20d", "20日对数收益率", FactorCategory.PRICE, "20日对数收益率"),
    _make_def("close_to_open_ret", "隔夜收益率", FactorCategory.PRICE, "今开对比昨收收益率"),
    _make_def("open_to_close_ret", "日内收益率", FactorCategory.PRICE, "今收对比今开收益率"),
    _make_def("high_to_low_ratio", "日内振幅比", FactorCategory.PRICE, "最高价对最低价比例"),
    _make_def("price_position_52w", "52周价格位置", FactorCategory.PRICE, "当前价在52周高低点区间的位置"),
    _make_def("price_pct_52w_high", "距52周最高点幅度", FactorCategory.PRICE, "距52周最高价偏离百分比"),
    _make_def("price_pct_52w_low", "距52周最低点幅度", FactorCategory.PRICE, "距52周最低价偏离百分比"),
    _make_def("gap_up_pct", "向上跳空幅度", FactorCategory.PRICE, "向上跳空开盘比例"),
    _make_def("gap_down_pct", "向下跳空幅度", FactorCategory.PRICE, "向下跳空开盘比例"),

    # 2. Trend (23)
    _make_def("sma_5", "5日简单移动平均", FactorCategory.TREND, "5日SMA"),
    _make_def("sma_10", "10日简单移动平均", FactorCategory.TREND, "10日SMA"),
    _make_def("sma_20", "20日简单移动平均", FactorCategory.TREND, "20日SMA"),
    _make_def("sma_60", "60日简单移动平均", FactorCategory.TREND, "60日SMA"),
    _make_def("sma_120", "120日简单移动平均", FactorCategory.TREND, "120日SMA"),
    _make_def("sma_200", "200日简单移动平均", FactorCategory.TREND, "200日SMA"),
    _make_def("ema_5", "5日指数移动平均", FactorCategory.TREND, "5日EMA"),
    _make_def("ema_12", "12日指数移动平均", FactorCategory.TREND, "12日EMA"),
    _make_def("ema_26", "26日指数移动平均", FactorCategory.TREND, "26日EMA"),
    _make_def("macd_line", "MACD快慢线差(DIF)", FactorCategory.TREND, "12与26日EMA差值"),
    _make_def("macd_signal", "MACD信号线(DEA)", FactorCategory.TREND, "DIF的9日EMA"),
    _make_def("macd_hist", "MACD柱状图", FactorCategory.TREND, "DIF与DEA差值未放大倍数"),
    _make_def("adx_14", "14日平均定向移动指数", FactorCategory.TREND, "ADX 14"),
    _make_def("di_plus_14", "14日正向定向指标", FactorCategory.TREND, "+DI 14"),
    _make_def("di_minus_14", "14日负向定向指标", FactorCategory.TREND, "-DI 14"),
    _make_def("aroon_up", "阿隆上升线", FactorCategory.TREND, "Aroon Up 25"),
    _make_def("aroon_down", "阿隆下降线", FactorCategory.TREND, "Aroon Down 25"),
    _make_def("aroon_osc", "阿隆振荡指标", FactorCategory.TREND, "Aroon Oscillator"),
    _make_def("trix_12", "三重指数平滑平均(TRIX)", FactorCategory.TREND, "TRIX 12"),
    _make_def("trix_signal", "TRIX信号线", FactorCategory.TREND, "TRIX 9日SMA"),
    _make_def("kdj_k", "KDJ-K值", FactorCategory.TREND, "KDJ K值"),
    _make_def("kdj_d", "KDJ-D值", FactorCategory.TREND, "KDJ D值"),
    _make_def("kdj_j", "KDJ-J值", FactorCategory.TREND, "KDJ J值"),

    # 3. Momentum (18)
    _make_def("rsi_6", "6日相对强弱指标", FactorCategory.MOMENTUM, "RSI 6"),
    _make_def("rsi_12", "12日相对强弱指标", FactorCategory.MOMENTUM, "RSI 12"),
    _make_def("rsi_24", "24日相对强弱指标", FactorCategory.MOMENTUM, "RSI 24"),
    _make_def("stoch_rsi_k", "随机RSI K值", FactorCategory.MOMENTUM, "StochRSI K"),
    _make_def("stoch_rsi_d", "随机RSI D值", FactorCategory.MOMENTUM, "StochRSI D"),
    _make_def("cci_14", "14日顺势指标", FactorCategory.MOMENTUM, "CCI 14"),
    _make_def("cci_20", "20日顺势指标", FactorCategory.MOMENTUM, "CCI 20"),
    _make_def("willr_14", "14日威廉指标", FactorCategory.MOMENTUM, "Williams %R 14"),
    _make_def("roc_5", "5日变动率", FactorCategory.MOMENTUM, "ROC 5"),
    _make_def("roc_10", "10日变动率", FactorCategory.MOMENTUM, "ROC 10"),
    _make_def("roc_20", "20日变动率", FactorCategory.MOMENTUM, "ROC 20"),
    _make_def("roc_60", "60日变动率", FactorCategory.MOMENTUM, "ROC 60"),
    _make_def("tsi_13_25", "真实强度指数", FactorCategory.MOMENTUM, "TSI 13 25"),
    _make_def("uo_7_14_28", "终极振荡指标", FactorCategory.MOMENTUM, "Ultimate Oscillator"),
    _make_def("ao_5_34", "动量震荡指标(AO)", FactorCategory.MOMENTUM, "Awesome Oscillator"),
    _make_def("momentum_10", "10日动量", FactorCategory.MOMENTUM, "Momentum 10"),
    _make_def("momentum_20", "20日动量", FactorCategory.MOMENTUM, "Momentum 20"),
    _make_def("momentum_60", "60日动量", FactorCategory.MOMENTUM, "Momentum 60"),

    # 4. Volatility / Risk (20)
    _make_def("volatility_5d", "5日年化波动率", FactorCategory.VOLATILITY, "5日日收益率年化标准差"),
    _make_def("volatility_20d", "20日年化波动率", FactorCategory.VOLATILITY, "20日年化波动率"),
    _make_def("volatility_60d", "60日年化波动率", FactorCategory.VOLATILITY, "60日年化波动率"),
    _make_def("volatility_240d", "240日年化波动率", FactorCategory.VOLATILITY, "240日年化波动率"),
    _make_def("atr_14", "14日真实波幅(ATR)", FactorCategory.VOLATILITY, "ATR 14"),
    _make_def("atr_20", "20日真实波幅(ATR)", FactorCategory.VOLATILITY, "ATR 20"),
    _make_def("natr_14", "14日归一化ATR", FactorCategory.VOLATILITY, "NATR 14"),
    _make_def("bbands_upper", "布林线上轨", FactorCategory.VOLATILITY, "Bollinger Upper"),
    _make_def("bbands_middle", "布林线中轨", FactorCategory.VOLATILITY, "Bollinger Middle"),
    _make_def("bbands_lower", "布林线下轨", FactorCategory.VOLATILITY, "Bollinger Lower"),
    _make_def("bbands_bandwidth", "布林线带宽", FactorCategory.VOLATILITY, "Bollinger Bandwidth"),
    _make_def("bbands_pct_b", "布林线%B指标", FactorCategory.VOLATILITY, "%B"),
    _make_def("kc_upper", "肯特纳通道上轨", FactorCategory.VOLATILITY, "KC Upper"),
    _make_def("kc_middle", "肯特纳通道中轨", FactorCategory.VOLATILITY, "KC Middle"),
    _make_def("kc_lower", "肯特纳通道下轨", FactorCategory.VOLATILITY, "KC Lower"),
    _make_def("donchian_high", "唐奇安通道上轨", FactorCategory.VOLATILITY, "Donchian High"),
    _make_def("donchian_low", "唐奇安通道下轨", FactorCategory.VOLATILITY, "Donchian Low"),
    _make_def("var_95_20d", "20日 95% 在轨 VaR", FactorCategory.VOLATILITY, "Value at Risk 95%"),
    _make_def("cvar_95_20d", "20日 95% 在轨 CVaR", FactorCategory.VOLATILITY, "Conditional VaR 95%"),
    _make_def("max_drawdown_60d", "60日最大回撤", FactorCategory.VOLATILITY, "Max Drawdown 60d"),

    # 5. Liquidity (19)
    _make_def("volume_sma_5", "5日成交量移动平均", FactorCategory.LIQUIDITY, "Volume SMA 5"),
    _make_def("volume_sma_20", "20日成交量移动平均", FactorCategory.LIQUIDITY, "Volume SMA 20"),
    _make_def("volume_ratio_5_20", "量比(5/20日)", FactorCategory.LIQUIDITY, "Volume Ratio 5/20"),
    _make_def("turnover_rate_sma_5", "5日换手率均值", FactorCategory.LIQUIDITY, "Turnover SMA 5"),
    _make_def("turnover_rate_sma_20", "20日换手率均值", FactorCategory.LIQUIDITY, "Turnover SMA 20"),
    _make_def("amihud_illiquidity_20d", "20日 Amihud 非流动性", FactorCategory.LIQUIDITY, "Amihud Illiquidity Ratio"),
    _make_def("mfi_14", "14日资金流量指标(MFI)", FactorCategory.LIQUIDITY, "MFI 14"),
    _make_def("cmf_20", "20日佳庆资金流量(CMF)", FactorCategory.LIQUIDITY, "CMF 20"),
    _make_def("obv", "能量潮指标(OBV)", FactorCategory.LIQUIDITY, "OBV"),
    _make_def("obv_sma_20", "20日OBV移动平均", FactorCategory.LIQUIDITY, "OBV SMA 20"),
    _make_def("pvt", "价量趋势指标(PVT)", FactorCategory.LIQUIDITY, "Price Volume Trend"),
    _make_def("nvi", "负成交量指数(NVI)", FactorCategory.LIQUIDITY, "Negative Volume Index"),
    _make_def("pvi", "正成交量指数(PVI)", FactorCategory.LIQUIDITY, "Positive Volume Index"),
    _make_def("eom_14", "14日简易波动指标(EOM)", FactorCategory.LIQUIDITY, "Ease of Movement"),
    _make_def("ad_line", "累积/派发线(A/D)", FactorCategory.LIQUIDITY, "Accumulation/Distribution"),
    _make_def("volume_std_20d", "20日成交量标准差", FactorCategory.LIQUIDITY, "Volume Std 20d"),
    _make_def("volume_skew_20d", "20日成交量偏度", FactorCategory.LIQUIDITY, "Volume Skew 20d"),
    _make_def("bid_ask_spread_est", "买卖价差估计", FactorCategory.LIQUIDITY, "Bid-Ask Spread Estimate"),
    _make_def("liquidity_ratio_20d", "20日流动性比率", FactorCategory.LIQUIDITY, "Liquidity Ratio"),

    # 6. Valuation (15)
    _make_def("pe_ttm", "市盈率(TTM)", FactorCategory.VALUATION, "P/E TTM"),
    _make_def("pe_lyr", "市盈率(静)", FactorCategory.VALUATION, "P/E LYR"),
    _make_def("pb_mrq", "市净率(MRQ)", FactorCategory.VALUATION, "P/B MRQ"),
    _make_def("ps_ttm", "市销率(TTM)", FactorCategory.VALUATION, "P/S TTM"),
    _make_def("pcf_ttm", "市现率(TTM)", FactorCategory.VALUATION, "P/CF TTM"),
    _make_def("ev_ebitda", "企业价值/EBITDA", FactorCategory.VALUATION, "EV / EBITDA"),
    _make_def("dividend_yield", "股息率", FactorCategory.VALUATION, "Dividend Yield"),
    _make_def("earnings_yield", "盈利收益率(E/P)", FactorCategory.VALUATION, "Earnings Yield (1/PE)"),
    _make_def("book_to_market", "账面市值比(B/P)", FactorCategory.VALUATION, "Book to Market (1/PB)"),
    _make_def("sales_to_price", "销售价格比(S/P)", FactorCategory.VALUATION, "Sales to Price (1/PS)"),
    _make_def("cash_to_price", "现金价格比(CF/P)", FactorCategory.VALUATION, "Cash to Price (1/PCF)"),
    _make_def("peg_ratio", "PEG指标", FactorCategory.VALUATION, "PEG Ratio"),
    _make_def("enterprise_value", "企业价值(EV)", FactorCategory.VALUATION, "Enterprise Value"),
    _make_def("market_cap", "总市值", FactorCategory.VALUATION, "Total Market Cap"),
    _make_def("circulating_market_cap", "流通市值", FactorCategory.VALUATION, "Circulating Market Cap"),

    # 7. Quality (20)
    _make_def("roe_ttm", "净资产收益率(ROE TTM)", FactorCategory.QUALITY, "ROE TTM"),
    _make_def("roa_ttm", "总资产收益率(ROA TTM)", FactorCategory.QUALITY, "ROA TTM"),
    _make_def("roic_ttm", "投入资本回报率(ROIC)", FactorCategory.QUALITY, "ROIC TTM"),
    _make_def("gross_margin", "毛利率", FactorCategory.QUALITY, "Gross Margin"),
    _make_def("net_margin", "净利率", FactorCategory.QUALITY, "Net Margin"),
    _make_def("operating_margin", "营业利润率", FactorCategory.QUALITY, "Operating Margin"),
    _make_def("ebitda_margin", "EBITDA利润率", FactorCategory.QUALITY, "EBITDA Margin"),
    _make_def("asset_turnover", "总资产周转率", FactorCategory.QUALITY, "Asset Turnover"),
    _make_def("inventory_turnover", "存货周转率", FactorCategory.QUALITY, "Inventory Turnover"),
    _make_def("receivables_turnover", "应收账款周转率", FactorCategory.QUALITY, "Receivables Turnover"),
    _make_def("current_ratio", "流动比率", FactorCategory.QUALITY, "Current Ratio"),
    _make_def("quick_ratio", "速动比率", FactorCategory.QUALITY, "Quick Ratio"),
    _make_def("cash_ratio", "现金比率", FactorCategory.QUALITY, "Cash Ratio"),
    _make_def("debt_to_assets", "资产负债率", FactorCategory.QUALITY, "Debt to Assets"),
    _make_def("debt_to_equity", "产权比率(债务权益比)", FactorCategory.QUALITY, "Debt to Equity"),
    _make_def("interest_coverage", "利息保障倍数", FactorCategory.QUALITY, "Interest Coverage"),
    _make_def("free_cash_flow_to_revenue", "自由现金流收入比", FactorCategory.QUALITY, "FCF / Revenue"),
    _make_def("accruals_ratio", "应计比率", FactorCategory.QUALITY, "Accruals Ratio"),
    _make_def("dupont_roe", "杜邦拆解ROE", FactorCategory.QUALITY, "DuPont ROE"),
    _make_def("piotroski_f_score", "Piotroski F-Score", FactorCategory.QUALITY, "Piotroski F-Score (0-9)"),

    # 8. Growth (16)
    _make_def("revenue_growth_yoy", "营业收入同比增长率", FactorCategory.GROWTH, "Revenue YoY Growth"),
    _make_def("net_profit_growth_yoy", "净利润同比增长率", FactorCategory.GROWTH, "Net Profit YoY Growth"),
    _make_def("operating_profit_growth_yoy", "营业利润同比增长率", FactorCategory.GROWTH, "Operating Profit YoY Growth"),
    _make_def("eps_growth_yoy", "每股收益同比增长率", FactorCategory.GROWTH, "EPS YoY Growth"),
    _make_def("fcf_growth_yoy", "自由现金流同比增长率", FactorCategory.GROWTH, "FCF YoY Growth"),
    _make_def("total_asset_growth_yoy", "总资产同比增长率", FactorCategory.GROWTH, "Total Asset YoY Growth"),
    _make_def("equity_growth_yoy", "净资产同比增长率", FactorCategory.GROWTH, "Equity YoY Growth"),
    _make_def("revenue_cagr_3y", "3年复合营业收入增长率", FactorCategory.GROWTH, "3Y Revenue CAGR"),
    _make_def("net_profit_cagr_3y", "3年复合净利润增长率", FactorCategory.GROWTH, "3Y Net Profit CAGR"),
    _make_def("revenue_qoq", "营业收入环比增长率", FactorCategory.GROWTH, "Revenue QoQ Growth"),
    _make_def("net_profit_qoq", "净利润环比增长率", FactorCategory.GROWTH, "Net Profit QoQ Growth"),
    _make_def("gross_profit_growth_yoy", "毛利润同比增长率", FactorCategory.GROWTH, "Gross Profit YoY Growth"),
    _make_def("ebitda_growth_yoy", "EBITDA同比增长率", FactorCategory.GROWTH, "EBITDA YoY Growth"),
    _make_def("operating_cash_flow_growth_yoy", "经营现金流同比增长率", FactorCategory.GROWTH, "OCF YoY Growth"),
    _make_def("sales_surprise", "营收超预期比例", FactorCategory.GROWTH, "Sales Surprise"),
    _make_def("earnings_surprise", "盈利超预期比例", FactorCategory.GROWTH, "Earnings Surprise"),

    # 9. Sentiment (12)
    _make_def("news_sentiment_3d", "3日新闻情绪均值", FactorCategory.SENTIMENT, "News Sentiment 3d"),
    _make_def("news_sentiment_7d", "7日新闻情绪均值", FactorCategory.SENTIMENT, "News Sentiment 7d"),
    _make_def("news_volume_3d", "3日新闻关注热度", FactorCategory.SENTIMENT, "News Count 3d"),
    _make_def("social_sentiment_3d", "3日社交情绪得分", FactorCategory.SENTIMENT, "Social Sentiment 3d"),
    _make_def("analyst_rating_mean", "分析师评级均值", FactorCategory.SENTIMENT, "Analyst Rating Mean"),
    _make_def("analyst_target_price_upside", "目标价预期涨幅", FactorCategory.SENTIMENT, "Target Price Upside"),
    _make_def("earnings_revision_30d", "30日盈利预测上调比例", FactorCategory.SENTIMENT, "Earnings Revision 30d"),
    _make_def("institution_holding_pct", "机构持股比例", FactorCategory.SENTIMENT, "Institutional Holding %"),
    _make_def("margin_trading_ratio", "融资融券交易占比", FactorCategory.SENTIMENT, "Margin Trading Ratio"),
    _make_def("limit_up_count_20d", "20日涨停天数", FactorCategory.SENTIMENT, "Limit Up Count 20d"),
    _make_def("limit_down_count_20d", "20日跌停天数", FactorCategory.SENTIMENT, "Limit Down Count 20d"),
    _make_def("suspension_flag", "停牌标识", FactorCategory.SENTIMENT, "Suspension Flag"),

    # 10. Cross-sectional / Base Composite (10)
    _make_def("size_factor", "规模因子(对数市值)", FactorCategory.CROSS_SECTIONAL, "Log Market Cap"),
    _make_def("value_composite", "综合估值因子", FactorCategory.CROSS_SECTIONAL, "Composite Valuation Factor"),
    _make_def("momentum_composite", "综合动量因子", FactorCategory.CROSS_SECTIONAL, "Composite Momentum Factor"),
    _make_def("quality_composite", "综合质量因子", FactorCategory.CROSS_SECTIONAL, "Composite Quality Factor"),
    _make_def("growth_composite", "综合成长因子", FactorCategory.CROSS_SECTIONAL, "Composite Growth Factor"),
    _make_def("volatility_composite", "综合低波动因子", FactorCategory.CROSS_SECTIONAL, "Composite Low-Vol Factor"),
    _make_def("liquidity_composite", "综合流动性因子", FactorCategory.CROSS_SECTIONAL, "Composite Liquidity Factor"),
    _make_def("sentiment_composite", "综合情绪因子", FactorCategory.CROSS_SECTIONAL, "Composite Sentiment Factor"),
    _make_def("multi_factor_score", "多因子打分", FactorCategory.CROSS_SECTIONAL, "Multi-Factor Composite Score"),
    _make_def("industry_neutral_momentum", "行业中性化动量", FactorCategory.CROSS_SECTIONAL, "Industry Neutral Momentum"),
]
